/// Flutter icons AromaIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AromaIcons
///      fonts:
///       - asset: fonts/AromaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AromaIcons {
  AromaIcons._();

  static const _kFontFam = 'AromaIcons';
  static const _kFontPkg = null;

  static const IconData einstellung = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData impressum = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telefon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warenkorb = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bestellung = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
